### ISSUE TITLE
Enhancement: Non-Ascii Character Support in templates

### ISSUE THREAD

**Issue by netopsengineer** [cmason3/jinjafx_server#23]
Hey @cmason3!

I am trying to template out some documentation, README's and the like that contain Emoji's, and I noticed that `jinjafx_server`, will not allow them to be rendered: 

`ERROR Non ASCII Character(s) in 'template.j2'`

I initially thought that `jinja2` simply didn't support it, but when trying another random online template rendering site, it is able to handle them.  Is it possible to add support for this?

Here is an example template, I am using the symbol based emoji's, and not the short hand `:emoji:` syntax, due to the markdown flavor/render only displaying the symbol based emoji's.

```jinja
## Get Started

To **Install** the dependencies and create a `virtualenv` once Poetry is installed:

**Clone** the project.

`git clone {{ base_git_url }}`

...snipped

That's it!  You're ready to go! 🎉
```

**Comment by cmason3** [comment]
It is due to a limitation in Google Chrome's implementation of `window.btoa` - for some unknown reason it doesn't actually like non-ASCII characters, which sort of defeats the whole point of what Base64 encoding is for.

When using Emojis or other non-ASCII characters within a template, the `btoa` function fails with the following error:

```
DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
```

There are a couple of options:

1. Don't use `window.btoa` and `window.atob` and use an external JavaScript library for Base64 (i.e. `js-base64') that handles non-ASCII characters, but I am trying to cut down the amount of external JavaScript libraries I am using as I was using quite a few.
2. I have had some success using the `utf8` JavaScript library, but this is another external library. I was hoping I could use the `TextEncoder()` and `TextDecoder()` native methods, but `TextDecoder()` can't seem to handle Python Utf8 encoding.

I didn't think there was a massive need for non-ASCII characters, so I took the easy option and it stops people uploading binary data in templates.

I have noticed you are doing Markdown - we do support native rendering of Markdown, e.g:

```
<output:md "Output">
## Get Started

To **Install** the dependencies and create a `virtualenv` once Poetry is installed:

**Clone** the project.

`git clone {{ base_git_url }}`

...snipped

That's it!  You're ready to go! :tada:
</output>
```

If this isn't what you are after then I will investigate using `js-base64` instead.

**Comment by netopsengineer** [comment]
>I have noticed you are doing Markdown - we do support native rendering of Markdown, e.g: ..

I planned on using that exact feature, but the only challenge is that `:tada:` is not rendered by Bitbucket, or a very limited set of those short form emoji references rather, but using the actual non-ascii emoji icon, would show up, which is what landed me into the non-ASCII characters problem.  Does the `jinjafx_cli` also have the same limitation?  I could perhaps write a script to handle the repeat operations if so, but it certainly is hard to beat the user experience of doing everything in the browser.

With the combination of input forms, and the output features you have added, it makes it perfect to save DataTemplates in a repo for folks to create consistent markup for repeat documentation tasks and the like!

**Comment by cmason3** [comment]
This is purely an issue with the web version as `window.btoa` isn't able to encode multibyte characters which are required for Emojis. Please can you try again using https://jinjafx.io as I have made an amendment which should now allow Unicode and Emojis within templates?
